# Generated by Django 4.1.4 on 2024-04-12 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0008_profile_facebook_link_profile_homepage_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='homepage_link',
            new_name='portfolio_link',
        ),
    ]
